export const Strings = {
  fr: {
    appName: "Magic World",
    play: "Jouer",
    color: "Colorier",
    bravo: "Bravo !",
    tryAgain: "Essaie encore !",
    mathGame: "Mathématiques",
    logicGame: "Logique",
    diffGame: "Différences",
    hangmanGame: "Pendu",
    readingGame: "Lecture",
    jokesGame: "Blagues",
    takePhoto: "Prendre une photo",
    pickImage: "Depuis la galerie",
    blankPage: "Page blanche",
    save: "Sauvegarder",
    back: "Retour",
    score: "Score",
    level: "Niveau",
    loading: "Chargement...",
    permissionDenied: "Permission refusée",
    library: "Bibliothèque",
    nouveau: "Nouveau",
    moi: "Moi",
    delete: "Supprimer",
    share: "Partager",
    pin: "Épingler",
    glitter: "Paillettes",
    selectGlitter: "Choisis tes paillettes",
    done: "C'est prêt !",
    understand: "J'ai compris !",
    help: "Besoin d'aide ?",
    next: "Suivant",
    skip: "Sauter le niveau",
    tutorialAdd: "On ajoute des pommes pour compter !",
    tutorialSub: "On enlève des objets !",
    tutorialMix: "Regarde bien le signe (+ ou -) !",
    tutorialMul: "Des paquets de nombres !",
    tutorialDiv: "On partage équitablement !",
    tutorialMental: "Calcul Mental ! Utilise ton génie.",
    helpAdd: (a, b, ans) => `Imagine que tu as ${a} bonbons et que je t'en donne ${b}. En tout, ça fait ${ans} !`,
    helpSub: (a, b, ans) => `Imagine que tu as ${a} pommes et que tu en manges ${b}. Il t'en reste ${ans} !`,
    helpMul: (a, b, ans) => `La multiplication, c'est ajouter plusieurs fois. ${a} fois ${b} fait ${ans} !`,
    helpDiv: (a, b, ans) => `Partage ${a} objets entre ${b} amis. Chacun en aura ${ans} !`,
    logicInstruction: "Glisse la forme au bon endroit !",
    readingSyllables: "Relie les sons identiques !",
    readingWords: "Relie les mots jumeaux !",
    readingPhrases: "Construis des petites histoires !",
    readingLogic: "Répons aux petites questions !",
    connect4Game: "Puissance 4",
    storiesGame: "Histoires",
    storiesSearchPlaceholder: "Chercher une histoire...",
    storiesAllSources: "Toutes",
    storiesAllTypes: "Tout",
    storiesTypeStory: "Histoires",
    storiesTypeSong: "Chansons",
    storiesSelected: "sélectionnée(s)",
    storiesPlay: "Écouter",
    storiesResume: "Reprendre",
    storiesSkipBack: "-10s",
    storiesSkipForward: "+10s",
    storiesPrevious: "Préc.",
    storiesNext: "Suiv.",
    storiesPlaylist: "File d'attente",
    storiesNowPlaying: "En cours…",
    storiesArtistFilter: "Filtrer par auteur / artiste…",
    storiesDurationUnder: (mins) => `< ${mins} min`,
    storiesDurationOver30: '> 30 s',
    storiesDurationUnder30: '< 30 s',
    storiesDurationAll: 'Toutes durées',
    storiesShowingCount: (shown, total) => `${shown} / ${total} histoires`,
    storiesLoadMore: 'Charger plus…',
    storiesSyncing: 'Mise à jour de la bibliothèque…',
    storiesFilterGenre: "Genre",
    storiesFilterArtist: "Artiste",
    storiesFilterAlbum: "Album",
    storiesFilterPack: "Pack",
    storiesAllPacks: "Tous les packs",
    storiesPackStoryCount: (n) => `${n} histoire${n > 1 ? 's' : ''}`,
    storiesPackUsageCount: (n) => `${n} écoute${n > 1 ? 's' : ''}`,
    storiesQueueTitle: (n) => `File d'attente (${n})`,
    storiesWillPlay: (n) => `${n} seront lues`,
    storiesPlayQueue: "Écouter la file",
    storiesParentalQueueHint: "Les histoires en vert seront lues en premier",
    storiesResumePlaylist: "Reprendre une histoire",
    storiesContinueAt: (time) => `Reprendre à ${time}`,
    storiesRebuildLibrary: "Rafraîchir la bibliothèque",
    storiesLibraryRebuilt: (n) => `${n} histoire(s) retrouvée(s) sur le disque`,
    storiesRebuildEmpty: "Aucun fichier audio trouvé sur le disque.",
    storiesSelectDownloaded: "Sélectionne des histoires téléchargées !",
    storiesNoProgress: "Aucune lecture en cours.",
    storiesStartNewPlaylist: "Nouvelle playlist",
    storiesSavePlaylist: "Sauver cette playlist",
    storiesSavePlaylistTitle: "Sauver la playlist",
    storiesSavePlaylistSubtitle: (n) => `${n} histoire${n > 1 ? 's' : ''} dans la file`,
    storiesSavePlaylistPlaceholder: "Nom de la playlist…",
    storiesSavePlaylistSuccess: "Playlist sauvegardée !",
    storiesSavePlaylistEmptyName: "Donne un nom à la playlist.",
    storiesSavedPlaylists: "Mes playlists",
    storiesSavedPlaylistsEmpty: "Aucune playlist sauvegardée.",
    storiesSavedStoryCount: (n) => `${n} histoire${n > 1 ? 's' : ''}`,
    storiesSavedContinueAt: (title, time) => `Reprendre « ${title} » à ${time}`,
    storiesLoadSavedQueue: "Charger",
    storiesDeleteSavedPlaylist: "Supprimer",
    storiesDeleteSavedPlaylistTitle: "Supprimer la playlist ?",
    storiesDeleteSavedPlaylistMessage: (name) => `Supprimer « ${name} » ?`,
    storiesReplaceProgressConfirm: "Tu as une lecture en cours. Veux-tu la reprendre ou lancer une nouvelle file ?",
    storiesEmpty: "Aucune histoire trouvée.",
    storiesEndingSoon: "Bientôt la fin !",
    storiesEndingSoonDetail: (n) => `Les histoires vont bientôt se terminer. Tu as écouté ${n} belle${n > 1 ? 's' : ''} histoire${n > 1 ? 's' : ''} !`,
    storiesGoodNight: "Bonne nuit !",
    storiesGoodNightDetail: (n) => `Tu as écouté ${n} histoire${n > 1 ? 's' : ''}. Il est temps de dormir.`,
    storiesBedtimeHint: "Appuie sur le bouton d'allumage pour éteindre la tablette.",
    storiesProgress: (current, total) => `Histoire ${current} sur ${total}`,
    parentalTitle: "Contrôle parental",
    parentalPin: "Code parent (4 chiffres)",
    parentalModeOff: "Désactivé",
    parentalModeTimer: "Timer",
    parentalModeStories: "Histoires",
    parentalTimerLabel: "Durée (minutes)",
    parentalStoriesLabel: "Nombre d'histoires",
    parentalActivate: "Activer",
    parentalDeactivate: "Désactiver",
    parentalActive: "Actif",
    parentalActiveTimer: (time) => `Timer : ${time} restantes`,
    parentalActiveStories: (n) => `${n} histoire(s) autorisée(s)`,
    parentalWrongPin: "Code incorrect",
    parentalWarningTitle: "Bientôt la fin !",
    parentalWarningTimer: (time) => `Plus que ${time} avant la fin du temps !`,
    parentalWarningStories: (n) => `Plus qu'une histoire et c'est fini ! (${n} restante)`,
    parentalLockTitle: "Bonne nuit !",
    parentalLockDetail: "Le temps est écoulé. Il est temps de se reposer.",
    parentalUnlock: "Déverrouiller",
    parentalUnlockLabel: "Code parent pour déverrouiller",
    parentalNeedDownload: "Télécharge au moins une histoire avant de lancer la lecture.",
    parentalMaxSelected: (n) => `Maximum ${n} histoire(s) pour cette session.`,
    parentalChangePin: "Réinitialiser le code parent",
    parentalResetMathHint: "Réponds à cette question pour réinitialiser le code :",
    parentalResetMathQuestion: (a, b) => `${a} × ${b} = ?`,
    parentalResetMathWrong: "Réponse incorrecte",
    parentalNewPin: "Nouveau code (4 chiffres)",
    parentalConfirmPin: "Confirmer le nouveau code",
    parentalSavePin: "Enregistrer le code",
    parentalPinSaved: "Code parent enregistré !",
    parentalPinMismatch: "Les nouveaux codes ne correspondent pas",
    parentalInvalidNewPin: "Le code doit contenir exactement 4 chiffres",
    parentalMinutesShort: "min",
    storiesCatalog: "Catalogue de packs",
    storiesCatalogHint: "Télécharge un pack pour débloquer les histoires qu'il contient.",
    storiesDownloadPack: "Télécharger",
    storiesResumeDownload: "Reprendre",
    storiesPackReady: (n) => `${n} histoire(s) ajoutée(s) à ta bibliothèque !`,
    storiesDeletePack: (title) => `Supprimer « ${title} » et toutes ses histoires ?`,
    storiesNoDownloaded: "Aucune histoire téléchargée. Va au catalogue pour en télécharger !",
    storiesOpenCatalog: "Ouvrir le catalogue",
    storiesDownloadsActive: "téléchargements en cours",
    storiesDownloadCancelled: "Téléchargement arrêté",
    storiesDownloadStoppedEmpty: "Le téléchargement a été interrompu.",
    storiesPartialSaved: (n) => `${n} histoire(s) déjà disponible(s) dans la bibliothèque`,
    storiesDownloadProgress: (written, total) => `${written} / ${total}`,
    storiesDownloadStatus: {
      preparing: "Préparation…",
      downloading: "Téléchargement…",
      paused: "En pause…",
      decrypting: "Déchiffrement…",
      unzipping: "Décompression…",
      extracting: "Extraction…",
      saving: "Enregistrement…",
    },
    playAlone: "Jouer Seul",
    playWithFriend: "Jouer à 2",
    yourTurn: "À toi !",
    friendTurn: "À ton ami(e) !",
    computerTurn: "L'ordinateur réfléchit...",
    redWins: "Les Rouges ont gagné !",
    yellowWins: "Les Jaunes ont gagné !",
    draw: "Match nul !",
    puzzleGame: "Puzzle",
    puzzleInstruction: "Glisse les pièces pour recomposer l'image !",
    choosePuzzleImage: "Choisis une image pour ton puzzle 🧩",
    chooseDifficulty: "Choisis la difficulté",
    piecesCount: (n) => `${n}x${n} (${n*n} pièces)`,
    savedPuzzles: "Puzzles en cours",
    continuePuzzle: "Continuer le puzzle",
    newPuzzle: "Nouveau puzzle",
    fromDevice: "Depuis l'appareil",
    myPhoto: "Ma Photo",
    failedToPickImage: "Impossible de charger l'image",
    enablePermissionsInSettings: "Active les permissions dans les réglages !",
    error: "Erreur",
    success: "Succès",
    listen: "Écouter la consigne",
    mrMmeTitle: "Monsieur et Madame",
    riddleTitle: "Devinettes",
    jokes: {
      mr_mme: [
        { q: "Monsieur et Madame 'Térieur' ont deux fils ?", a: "Alain et Alex ! (À l'intérieur et à l'extérieur)" },
        { q: "Monsieur et Madame 'Croche' ont une fille ?", a: "Sarah ! (Ça raccroche)" },
        { q: "Monsieur et Madame 'Bon' ont un fils ?", a: "Jean ! (Jean Bon... Jambon !)" },
        { q: "Monsieur et Madame 'Bambelle' ont une fille ?", a: "Larry ! (La ribambelle)" },
        { q: "Monsieur et Madame 'Di' ont une fille ?", a: "Ella ! (Elle a dit)" },
        { q: "Monsieur et Madame 'Ptitpeu' ont un fils ?", a: "Justin ! (Juste un petit peu)" },
        { q: "Monsieur et Madame 'Touille' ont un fils ?", a: "Sacha ! (Sacha Touille... Ça chatouille !)" },
        { q: "Monsieur et Madame 'Zarella' ont une fille ?", a: "Maude ! (Mozzarella)" },
        { q: "Monsieur et Madame 'Ouzi' ont un fils ?", a: "Jacques ! (Jacuzzi)" },
        { q: "Monsieur et Madame 'Covert' ont un fils ?", a: "Harry ! (Haricot vert)" },
        { q: "Monsieur et Madame 'Fraichit' ont une fille ?", a: "Sarah ! (Ça rafraîchit)" },
        { q: "Monsieur et Madame 'Proviste' ont un fils ?", a: "Alain ! (À l'improviste)" },
        { q: "Monsieur et Madame 'Fonfec' ont une fille ?", a: "Sophie ! (Sauf s'il fait sec)" },
        { q: "Monsieur et Madame 'Mauve' ont un fils ?", a: "Guy ! (Guimauve)" },
        { q: "Monsieur et Madame 'Assin' ont un fils ?", a: "Marc ! (Marcassin)" },
        { q: "Monsieur et Madame 'Honnette' ont une fille ?", a: "Camille ! (Camionnette)" },
        { q: "Monsieur et Madame 'Kiroule' ont un fils ?", a: "Pierre ! (Pierre qui roule...)" },
        { q: "Monsieur et Madame 'Conda' ont une fille ?", a: "Anna ! (Anaconda)" },
        { q: "Monsieur et Madame 'Saires' ont un fils ?", a: "Bruno ! (Buenos Aires)" },
        { q: "Monsieur et Madame 'Ponsable' ont une fille ?", a: "Thérèse ! (T'es responsable)" },
        { q: "Monsieur et Madame 'Rogne' ont un fils ?", a: "Yves ! (Ivrogne)" },
        { q: "Monsieur et Madame 'Peuplu' ont un fils ?", a: "Jean ! (J'en peux plus)" },
        { q: "Monsieur et Madame 'Dégoûte' ont une fille ?", a: "Emma ! (Elle m'a dégoûté)" },
        { q: "Monsieur et Madame 'Pareballes' ont un fils ?", a: "Gilles ! (Gilet pare-balles)" },
        { q: "Monsieur et Madame 'Mobyle' ont un fils ?", a: "Otto ! (Automobile)" },
        { q: "Monsieur et Madame 'Ateliste' ont un fils ?", a: "Phil ! (Philatéliste)" },
        { q: "Monsieur et Madame 'Rigole' ont un fils ?", a: "Jean ! (J'en rigole)" },
        { q: "Monsieur et Madame 'Ai-Marre' ont un fils ?", a: "Jean ! (J'en ai marre)" },
        { q: "Monsieur et Madame 'Cépasur' ont un fils ?", a: "Jean-Philippe ! (J'en suis pas sûr)" },
        { q: "Monsieur et Madame 'Fly' ont une fille ?", a: "Muguette ! (Mets guetter Fly...)" },
        { q: "Monsieur et Madame 'Plus' ont un fils ?", a: "Jean ! (J'en ai plus)" },
        { q: "Monsieur et Madame 'D'eau' ont un fils ?", a: "Jean ! (Jean d'eau...)" },
        { q: "Monsieur et Madame 'Versaire' ont un fils ?", a: "Yann ! (Anniversaire)" },
        { q: "Monsieur et Madame 'Aire' ont un fils ?", a: "Axel ! (Accélère !)" },
        { q: "Monsieur et Madame 'Hochet' ont un fils ?", a: "Rick ! (Ricocher)" },
        { q: "Monsieur et Madame 'Chon' ont un fils ?", a: "Paul ! (Polochon)" },
        { q: "Monsieur et Madame 'Ouille' ont un fils ?", a: "Pat ! (Patrouille)" },
        { q: "Monsieur et Madame 'Némar' ont un fils ?", a: "Jean ! (J'en ai marre)" },
        { q: "Monsieur et Madame 'Atout' ont une fille ?", a: "Sarah ! (Ça rase tout)" },
        { q: "Monsieur et Madame 'Palair' ont une fille ?", a: "Sarah ! (Ça n'a pas l'air)" },
        { q: "Monsieur et Madame 'O'Fraiche' ont une fille ?", a: "Sarah ! (Sarah Fraiche... Ça rafraîchit !)" },
        { q: "Monsieur et Madame 'Gueuler' ont un fils ?", a: "Ivan ! (Il va gueuler !)" },
        { q: "Monsieur et Madame 'In' ont un fils ?", a: "Mouss ! (Mouss'In... Mousseline !)" },
        { q: "Monsieur et Madame 'Enfaillite' ont une fille ?", a: "Mélusine ! (Mets l'usine en faillite !)" },
        { q: "Monsieur et Madame 'Lenvie' ont une fille ?", a: "Mélanie ! (Mets l'envie !)" },
        { q: "Monsieur et Madame 'Aipon' ont un fils ?", a: "Rémi ! (Réponds-moi !)" },
        { q: "Monsieur et Madame 'Teau' ont un fils ?", a: "Marceau ! (Marteau)" },
        { q: "Monsieur et Madame 'Enslair' ont un fils ?", a: "Jacques ! (J'ai les mains en l'air !)" },
        { q: "Monsieur et Madame 'Scouché' ont un fils ?", a: "Félicien ! (Fait l'y s'coucher !)" },
        { q: "Monsieur et Madame 'Timbe' ont un fils ?", a: "Marceau ! (Morceau de timbre)" }
      ],
      devinettes: [
        { q: "Qu'est-ce qui est jaune et qui attend ?", a: "Jonathan !" },
        { q: "Qu'est-ce qui est vert et qui monte et qui descend ?", a: "Un petit pois dans un ascenseur !" },
        { q: "Qu'est-ce qui est rouge et qui clignote ?", a: "Une fraise qui n'a pas la priorité !" },
        { q: "Je suis plein de trous mais je retiens l'eau. Qui suis-je ?", a: "Une éponge !" },
        { q: "Plus je sèche, plus je deviens mouillé. Qui suis-je ?", a: "Une serviette !" },
        { q: "Qu'est-ce qui tombe sans se faire mal ?", a: "La nuit !" },
        { q: "Qu'est-ce qui a des dents mais ne mord jamais ?", a: "Un peigne !" },
        { q: "Je commence par E, je finis par E, mais je ne contiens qu'une seule lettre. Qui suis-je ?", a: "Une enveloppe !" },
        { q: "Qu'est-ce qui t'appartient, mais que les autres utilisent plus que toi ?", a: "Ton prénom !" },
        { q: "Qu'est-ce qui a des racines mais ne pousse jamais ?", a: "Une dent !" },
        { q: "Qu'est-ce qui a un oeil mais ne voit rien ?", a: "Une aiguille !" },
        { q: "Qu'est-ce qui a des pieds mais ne marche pas ?", a: "Un tabouret !" },
        { q: "Qu'est-ce qui a une tête mais pas de corps ?", a: "Une pièce de monnaie !" },
        { q: "Qu'est-ce qui a un dos mais pas de ventre ?", a: "Une chaise !" },
        { q: "Qu'est-ce qui a un cou mais pas de tête ?", a: "Une bouteille !" },
        { q: "Qu'est-ce qui a une langue mais ne parle pas ?", a: "Une chaussure !" },
        { q: "Qu'est-ce qui a des oreilles mais n'entend rien ?", a: "Un champ de maïs !" },
        { q: "Qu'est-ce qui a des dents mais ne mange pas ?", a: "Une scie !" },
        { q: "Qu'est-ce qui a un lit mais ne dort jamais ?", a: "Une rivière !" },
        { q: "Qu'est-ce qui a des ailes mais ne vole pas ?", a: "Un moulin !" },
        { q: "Qu'est-ce qui a des bras mais pas de mains ?", a: "Un fauteuil !" },
        { q: "Qu'est-ce qui a un chapeau mais pas de tête ?", a: "Un champignon !" },
        { q: "Qu'est-ce qui a une clé mais pas de porte ?", a: "Un piano !" },
        { q: "Qu'est-ce qui a des feuilles mais pas d'arbre ?", a: "Un livre !" },
        { q: "Qu'est-ce qui court mais n'a pas de jambes ?", a: "Le temps !" },
        { q: "Qu'est-ce qui monte quand la pluie tombe ?", a: "Un parapluie !" },
        { q: "Qu'est-ce qui suit toujours son propriétaire ?", a: "Son ombre !" },
        { q: "Qu'est-ce qui peut faire le tour du monde en restant dans un coin ?", a: "Un timbre !" },
        { q: "Qu'est-ce qui a quatre roues et des mouches ?", a: "Un camion de poubelles !" },
        { q: "Quel animal a le plus de dents ?", a: "La petite souris !" },
        { q: "Quel est l'animal le plus rapide du monde ?", a: "Le pou, car il est toujours sur la tête !" },
        { q: "Quel est le sport préféré des insectes ?", a: "Le criquet !" },
        { q: "Pourquoi les gorilles ont-ils de grosses narines ?", a: "Parce qu'ils ont de gros doigts !" },
        { q: "Quel est le comble pour un électricien ?", a: "D'avoir des ampoules aux pieds !" },
        { q: "Quel est le comble pour un facteur ?", a: "D'être lettre mort !" },
        { q: "Quel est le comble pour un marin ?", a: "D'avoir le mal de terre !" },
        { q: "Quel est le comble pour un photographe ?", a: "De ne pas être dans le champ !" },
        { q: "Quel est le comble pour un plombier ?", a: "De prendre la fuite !" },
        { q: "Quel est le comble pour un prof de géo ?", a: "De ne pas être dans son assiette !" },
        { q: "Quel est le comble pour un pâtissier ?", a: "D'être dans le pétrin !" },
        { q: "Quel est le comble pour un boucher ?", a: "D'avoir un coeur d'artichaut !" },
        { q: "Quel est le comble pour un opticien ?", a: "De ne pas y voir clair !" },
        { q: "Quel est le comble pour un dentiste ?", a: "De trouver que la vie est dure !" },
        { q: "Quel est le comble pour un astronaute ?", a: "D'être dans la lune !" },
        { q: "Quel est le comble pour un magicien ?", a: "D'oublier son tour !" },
        { q: "Quel est le comble pour un sourd ?", a: "De ne pas s'entendre avec son voisin !" },
        { q: "Quel est le comble pour un jardinier ?", a: "De raconter des salades !" },
        { q: "Quel est le comble pour un horloger ?", a: "De ne pas avoir une seconde à lui !" },
        { q: "Quel est le comble pour un cuisinier ?", a: "De ne pas être dans son assiette !" },
        { q: "Quel est le comble pour un pompier ?", a: "De brûler d'envie !" }
      ]
    },
    voice: "fr-FR"
  },
  ar: {
    appName: "عالمي السحري",
    play: "لعب",
    color: "تلوين",
    bravo: "أحسنت !",
    tryAgain: "حاول مرة أخرى !",
    mathGame: "رياضيات",
    logicGame: "منطق",
    diffGame: "اختلافات",
    hangmanGame: "الرجل المشنوق",
    readingGame: "قراءة",
    jokesGame: "نكت",
    takePhoto: "التقط صورة",
    pickImage: "من المعرض",
    blankPage: "صفحة بيضاء",
    save: "حفظ",
    back: "رجوع",
    score: "النتيجة",
    level: "المستوى",
    loading: "جاري التحميل...",
    permissionDenied: "تم رفض الإذن",
    library: "المكتبة",
    nouveau: "جديد",
    moi: "أنا",
    delete: "حذف",
    share: "مشاركة",
    pin: "تثبيت",
    done: "جاهz !",
    understand: "فهمت !",
    help: "تحتاج مساعدة ؟",
    next: "التالي",
    skip: "تخطي المستوى",
    tutorialAdd: "نجمع التفاح لنعد !",
    tutorialSub: "نطرح الأشياء !",
    tutorialMix: "انظر جيدا للإشارة (+ أو -) !",
    tutorialMul: "مجموعات من الأرقام !",
    tutorialDiv: "نوزع بالتساوي !",
    tutorialMental: "حساب ذهني ! استعمل ذكاءك.",
    helpAdd: (a, b, ans) => `تخيل أن لديك ${a} حلوى وأعطيتك ${b}. المجموع هو ${ans} !`,
    helpSub: (a, b, ans) => `تخيل أن لديك ${a} تفاحة وأكلت ${b}. يبقى لديك ${ans} !`,
    helpMul: (a, b, ans) => `الضرب هو الجمع المتكرر. ${a} في ${b} يساوي ${ans} !`,
    helpDiv: (a, b, ans) => `وزع ${a} أشياء على ${b} أصدقاء. كل واحد سيأخذ ${ans} !`,
    logicInstruction: "اسحب الشكل للمكان الصحيح !",
    readingSyllables: "صل الأصوات المتطابقة !",
    readingWords: "صل الكلمات المتشابهة !",
    readingPhrases: "ابنِ قصصا قصيرة !",
    readingLogic: "أجب عن الأسئلة البسيطة !",
    connect4Game: "لعبة 4 في صف",
    storiesGame: "قصص",
    storiesSearchPlaceholder: "ابحث عن قصة...",
    storiesAllSources: "الكل",
    storiesAllTypes: "الكل",
    storiesTypeStory: "قصص",
    storiesTypeSong: "أغاني",
    storiesSelected: "مختارة",
    storiesPlay: "استمع",
    storiesResume: "تابع",
    storiesSelectDownloaded: "اختر قصصا محملة !",
    storiesNoProgress: "لا توجد قراءة جارية.",
    storiesEmpty: "لم يتم العثور على قصص.",
    storiesEndingSoon: "قريبا النهاية !",
    storiesEndingSoonDetail: (n) => `القصص ستنتهي قريبا. استمعت إلى ${n} قصة !`,
    storiesGoodNight: "تصبح على خير !",
    storiesGoodNightDetail: (n) => `استمعت إلى ${n} قصة. حان وقت النوم.`,
    storiesBedtimeHint: "اضغط على زر الطاقة لإطفاء الجهاز.",
    storiesProgress: (current, total) => `قصة ${current} من ${total}`,
    parentalTitle: "الرقابة الأبوية",
    parentalPin: "رمز الوالدين (4 أرقام)",
    parentalModeOff: "معطل",
    parentalModeTimer: "مؤقت",
    parentalModeStories: "قصص",
    parentalTimerLabel: "المدة (دقائق)",
    parentalStoriesLabel: "عدد القصص",
    parentalActivate: "تفعيل",
    parentalDeactivate: "إيقاف",
    parentalActive: "نشط",
    parentalActiveTimer: (time) => `مؤقت: ${time} متبقية`,
    parentalActiveStories: (n) => `${n} قصة مسموحة`,
    parentalWrongPin: "رمز غير صحيح",
    parentalWarningTitle: "قريبا النهاية !",
    parentalWarningTimer: (time) => `بقي ${time} قبل النهاية !`,
    parentalWarningStories: (n) => `قصة واحدة فقط وانتهى ! (${n} متبقية)`,
    parentalLockTitle: "تصبح على خير !",
    parentalLockDetail: "انتهى الوقت. حان وقت الراحة.",
    parentalUnlock: "فتح",
    parentalUnlockLabel: "رمز الوالدين للفتح",
    parentalNeedDownload: "حمّل قصة واحدة على الأقل قبل التشغيل.",
    parentalMaxSelected: (n) => `الحد الأقصى ${n} قصة لهذه الجلسة.`,
    parentalChangePin: "إعادة تعيين رمز الوالدين",
    parentalResetMathHint: "أجب على هذا السؤال لإعادة التعيين :",
    parentalResetMathQuestion: (a, b) => `${a} × ${b} = ?`,
    parentalResetMathWrong: "إجابة خاطئة",
    parentalNewPin: "رمز جديد (4 أرقام)",
    parentalConfirmPin: "تأكيد الرمز الجديد",
    parentalSavePin: "حفظ الرمز",
    parentalPinSaved: "تم حفظ رمز الوالدين !",
    parentalPinMismatch: "الرمزان الجديدان غير متطابقين",
    parentalInvalidNewPin: "يجب أن يتكون الرمز من 4 أرقام",
    parentalMinutesShort: "د",
    playAlone: "العب وحدك",
    playWithFriend: "العب مع صديق",
    yourTurn: "دورك !",
    friendTurn: "دور صديقك !",
    computerTurn: "الكمبيوتر يفكر...",
    redWins: "الأحمر فاز !",
    yellowWins: "الأصفر فاز !",
    draw: "تعادل !",
    puzzleGame: "بازل",
    puzzleInstruction: "اسحب القطع لتركيب الصورة!",
    choosePuzzleImage: "اختر صورة للبازل 🧩",
    chooseDifficulty: "اختر الصعوبة",
    piecesCount: (n) => `${n}x${n} (${n*n} قطعة)`,
    savedPuzzles: "بازل قيد التنفيذ",
    continuePuzzle: "أكمل البازل",
    newPuzzle: "بازل جديد",
    fromDevice: "من الجهاز",
    myPhoto: "صورتي",
    failedToPickImage: "فشل تحميل الصورة",
    enablePermissionsInSettings: "فعل الصلاحيات في الإعدادات !",
    error: "خطأ",
    success: "نجاح",
    listen: "استمع إلى التعليمات",
    mrMmeTitle: "السيد والسيدة",
    riddleTitle: "ألغاز",
    jokes: {
      mr_mme: [
        { q: "ما هو الشيء الذي له عين واحدة ولا يرى؟", a: "الإبرة !" },
        { q: "ما هو الشيء الذي يكتب ولا يقرأ؟", a: "القلم !" }
      ],
      devinettes: [
        { q: "ما هو الشيء الذي تذبحه وتبكي عليه؟", a: "البصل !" },
        { q: "ما هو الشيء الذي كلما زاد نقص؟", a: "العمر !" }
      ]
    },
    voice: "ar-SA"
  },
  ar_dz: {
    appName: "عالمي السحري",
    play: "نلعبو",
    color: "نلونو",
    bravo: "صحة ! يعطيك الصحة !",
    tryAgain: "عاود مرة خرى !",
    mathGame: "حساب",
    logicGame: "شكال",
    diffGame: "ختلافات",
    hangmanGame: "المشنوق",
    readingGame: "قراية",
    jokesGame: "ضحك",
    takePhoto: "نصوّر",
    pickImage: "من التصاور",
    blankPage: "ورقة بيضا",
    save: "نخبّي",
    back: "نولّي",
    score: "النقاط",
    level: "المستوى",
    loading: "راني نشارجي...",
    permissionDenied: "ماكاش تصريح",
    library: "الخزانة",
    nouveau: "جديد",
    moi: "أنا",
    delete: "نقلّع",
    share: "نبارطاجي",
    pin: "نثبّت",
    done: "واجد !",
    understand: "فهمت !",
    help: "تخصك معاونة ؟",
    next: "الجاي",
    skip: "نڤز المستوى",
    tutorialAdd: "نزيدo التفاح باش نحسبو !",
    tutorialSub: "نقلّعو الحاجات !",
    tutorialMix: "شوف مليح العلامة (+ ولا -) !",
    tutorialMul: "بزاف تاع أرقام !",
    tutorialDiv: "نقسمو بالعدل !",
    tutorialMental: "حساب في الراس ! وريني فهامتك.",
    helpAdd: (a, b, ans) => `تخيل عندك ${a} حلوى ونزيدلك ${b}. شحال يولي عندك؟ ${ans} !`,
    helpSub: (a, b, ans) => `تخيل عندك ${a} تفاحة وتاكل منها ${b}. شحال يبقى لك؟ ${ans} !`,
    helpMul: (a, b, ans) => `الضرب هو نجمعو بزاف مرات. ${a} في ${b} تعطينا ${ans} !`,
    helpDiv: (a, b, ans) => `نقسمو ${a} حاجة على ${b} صحابك. كل واحد يدي ${ans} !`,
    logicInstruction: "دير الشكل في بلاصتو !",
    readingSyllables: "ربط الصوات اللي كيف كيف !",
    readingWords: "ربط الكلمات اللي يتشابهو !",
    readingPhrases: "دير حكايات صغار !",
    readingLogic: "جاوب على هاد السوالات !",
    connect4Game: "لعبة 4 في صف",
    storiesGame: "قصص",
    storiesSearchPlaceholder: "ابحث عن قصة...",
    storiesAllSources: "الكل",
    storiesAllTypes: "الكل",
    storiesTypeStory: "قصص",
    storiesTypeSong: "أغاني",
    storiesSelected: "مختارة",
    storiesPlay: "استمع",
    storiesResume: "تابع",
    storiesSelectDownloaded: "اختر قصصا محملة !",
    storiesNoProgress: "لا توجد قراءة جارية.",
    storiesEmpty: "لم يتم العثور على قصص.",
    storiesEndingSoon: "قريبا النهاية !",
    storiesEndingSoonDetail: (n) => `القصص ستنتهي قريبا. استمعت إلى ${n} قصة !`,
    storiesGoodNight: "تصبح على خير !",
    storiesGoodNightDetail: (n) => `استمعت إلى ${n} قصة. حان وقت النوم.`,
    storiesBedtimeHint: "اضغط على زر الطاقة لإطفاء الجهاز.",
    storiesProgress: (current, total) => `قصة ${current} من ${total}`,
    parentalTitle: "الرقابة الأبوية",
    parentalPin: "كود الوالدين (4 أرقام)",
    parentalModeOff: "طافي",
    parentalModeTimer: "مؤقت",
    parentalModeStories: "قصص",
    parentalTimerLabel: "المدة (دقائق)",
    parentalStoriesLabel: "عدد القصص",
    parentalActivate: "فعّل",
    parentalDeactivate: "طفي",
    parentalActive: "شغال",
    parentalActiveTimer: (time) => `مؤقت: ${time} باقية`,
    parentalActiveStories: (n) => `${n} قصة مسموحة`,
    parentalWrongPin: "كود غالط",
    parentalWarningTitle: "قريبا النهاية !",
    parentalWarningTimer: (time) => `باقي ${time} ويسالي !`,
    parentalWarningStories: (n) => `قصة وحدة ويسالي ! (${n} باقية)`,
    parentalLockTitle: "تصبح على خير !",
    parentalLockDetail: "الوقت سالى. وقت الراحة.",
    parentalUnlock: "حل",
    parentalUnlockLabel: "كود الوالدين باش تحل",
    parentalNeedDownload: "حمّل قصة واحدة على الأقل قبل ما تسمع.",
    parentalMaxSelected: (n) => `ماكس ${n} قصة لهاد الوقت.`,
    parentalChangePin: "بدّل كود الوالدين",
    parentalResetMathHint: "جاوب على السؤال باش تبدّل الكود :",
    parentalResetMathQuestion: (a, b) => `${a} × ${b} = ?`,
    parentalResetMathWrong: "الجواب غالط",
    parentalNewPin: "كود جديد (4 أرقام)",
    parentalConfirmPin: "أكّد الكود الجديد",
    parentalSavePin: "سجّل الكود",
    parentalPinSaved: "تسجّل كود الوالدين !",
    parentalPinMismatch: "الكودين الجداد ما يطابقوش",
    parentalInvalidNewPin: "الكود لازم يكون 4 أرقام",
    parentalMinutesShort: "د",
    playAlone: "العب وحدك",
    yourTurn: "دالتك !",
    friendTurn: "دالة صاحبك !",
    computerTurn: "الكمبيوتر راه يخمم...",
    redWins: "الحمر ربحو !",
    yellowWins: "الصفر ربحو !",
    draw: "تعادل !",
    puzzleGame: "بازل",
    puzzleInstruction: "حط القطع في بلاصتهم باش تكمل التصويرة !",
    choosePuzzleImage: "خير تصويرة للبازل 🧩",
    chooseDifficulty: "خير شحال من قطعة",
    piecesCount: (n) => `${n}x${n} (${n*n} مرصو)`,
    savedPuzzles: "بازل ماراهش واجد",
    continuePuzzle: "كمل البازل",
    newPuzzle: "بازل جديد",
    fromDevice: "مل التليفون",
    myPhoto: "صورتي",
    failedToPickImage: "ما نجمتش نشارجي التصويرة",
    enablePermissionsInSettings: "فعل الصلاحيات فلي ريغلاج !",
    error: "كاين غلطة",
    success: "صحة",
    listen: "اسمع واش نديرو",
    mrMmeTitle: "السيد والسيدة",
    riddleTitle: "حجايات",
    jokes: {
      mr_mme: [
        { q: "حاجة تمشي بلا رجلين وتدخل بلا عينين؟", a: "الرسالة !" }
      ],
      devinettes: [
        { q: "حاجة تاكل وما تشبع، وإذا شربت الماء تموت؟", a: "النار !" },
        { q: "حاجة ترفد قنطار وما ترفدش مسمار؟", a: "البحر !" }
      ]
    },
    voice: "ar-SA"
  },
  en: {
    appName: "Magic World",
    play: "Play",
    color: "Color",
    bravo: "Well Done!",
    tryAgain: "Try Again!",
    mathGame: "Mathematics",
    logicGame: "Logic",
    diffGame: "Differences",
    hangmanGame: "Hangman",
    readingGame: "Reading",
    jokesGame: "Jokes",
    takePhoto: "Take a Photo",
    pickImage: "From Gallery",
    blankPage: "Blank Page",
    save: "Save",
    back: "Back",
    score: "Score",
    level: "Level",
    loading: "Loading...",
    permissionDenied: "Permission Denied",
    library: "Library",
    nouveau: "New",
    moi: "Me",
    delete: "Delete",
    share: "Share",
    pin: "Pin",
    done: "Done!",
    understand: "Got it!",
    help: "Need help?",
    next: "Next",
    skip: "Skip Level",
    tutorialAdd: "We add apples to count!",
    tutorialSub: "We take items away!",
    tutorialMix: "Look closely at the sign (+ or -)!",
    tutorialMul: "Groups of numbers!",
    tutorialDiv: "Share equally!",
    tutorialMental: "Mental Math! Use your genius.",
    helpAdd: (a, b, ans) => `Imagine you have ${a} candies and I give you ${b}. In total, that's ${ans}!`,
    helpSub: (a, b, ans) => `Imagine you have ${a} apples and you eat ${b}. You have ${ans} left!`,
    helpMul: (a, b, ans) => `Multiplication is adding multiple times. ${a} times ${b} is ${ans}!`,
    helpDiv: (a, b, ans) => `Share ${a} items among ${b} friends. Each will have ${ans}!`,
    logicInstruction: "Drag the shape to the right place!",
    readingSyllables: "Match the identical sounds!",
    readingWords: "Match the twin words!",
    readingPhrases: "Build short stories!",
    readingLogic: "Answer simple questions!",
    connect4Game: "Connect 4",
    storiesGame: "Stories",
    storiesSearchPlaceholder: "Search a story...",
    storiesAllSources: "All",
    storiesAllTypes: "All",
    storiesTypeStory: "Stories",
    storiesTypeSong: "Songs",
    storiesSelected: "selected",
    storiesPlay: "Listen",
    storiesResume: "Resume",
    storiesSkipBack: "-10s",
    storiesSkipForward: "+10s",
    storiesPrevious: "Prev",
    storiesNext: "Next",
    storiesPlaylist: "Playlist",
    storiesNowPlaying: "Now playing…",
    storiesArtistFilter: "Filter by author / artist…",
    storiesDurationUnder: (mins) => `< ${mins} min`,
    storiesDurationOver30: '> 30 s',
    storiesDurationUnder30: '< 30 s',
    storiesDurationAll: 'Toutes durées',
    storiesShowingCount: (shown, total) => `${shown} / ${total} stories`,
    storiesLoadMore: 'Load more…',
    storiesSyncing: 'Updating library…',
    storiesFilterAlbum: "Album",
    storiesFilterPack: "Pack",
    storiesAllPacks: "All packs",
    storiesPackStoryCount: (n) => `${n} ${n > 1 ? 'stories' : 'story'}`,
    storiesPackUsageCount: (n) => `${n} play${n > 1 ? 's' : ''}`,
    storiesQueueTitle: (n) => `Queue (${n})`,
    storiesWillPlay: (n) => `${n} will play`,
    storiesPlayQueue: "Play queue",
    storiesParentalQueueHint: "Green stories will play first",
    storiesResumePlaylist: "Resume a story",
    storiesContinueAt: (time) => `Resume at ${time}`,
    storiesRebuildLibrary: "Refresh library",
    storiesLibraryRebuilt: (n) => `${n} story(ies) found on disk`,
    storiesRebuildEmpty: "No audio files found on disk.",
    storiesSelectDownloaded: "Select downloaded stories!",
    storiesNoProgress: "No playback in progress.",
    storiesStartNewPlaylist: "New playlist",
    storiesSavePlaylist: "Save this playlist",
    storiesSavePlaylistTitle: "Save playlist",
    storiesSavePlaylistSubtitle: (n) => `${n} ${n > 1 ? 'stories' : 'story'} in queue`,
    storiesSavePlaylistPlaceholder: "Playlist name…",
    storiesSavePlaylistSuccess: "Playlist saved!",
    storiesSavePlaylistEmptyName: "Enter a playlist name.",
    storiesSavedPlaylists: "My playlists",
    storiesSavedPlaylistsEmpty: "No saved playlists.",
    storiesSavedStoryCount: (n) => `${n} ${n > 1 ? 'stories' : 'story'}`,
    storiesSavedContinueAt: (title, time) => `Resume « ${title} » at ${time}`,
    storiesLoadSavedQueue: "Load",
    storiesDeleteSavedPlaylist: "Delete",
    storiesDeleteSavedPlaylistTitle: "Delete playlist?",
    storiesDeleteSavedPlaylistMessage: (name) => `Delete « ${name} »?`,
    storiesReplaceProgressConfirm: "You have playback in progress. Resume it or start a new queue?",
    storiesEmpty: "No stories found.",
    storiesEndingSoon: "Almost done!",
    storiesEndingSoonDetail: (n) => `Stories ending soon. You listened to ${n} wonderful ${n > 1 ? 'stories' : 'story'}!`,
    storiesGoodNight: "Good night!",
    storiesGoodNightDetail: (n) => `You listened to ${n} ${n > 1 ? 'stories' : 'story'}. Time to sleep.`,
    storiesBedtimeHint: "Press the power button to turn off the tablet.",
    storiesProgress: (current, total) => `Story ${current} of ${total}`,
    parentalTitle: "Parental Control",
    parentalPin: "Parent code (4 digits)",
    parentalModeOff: "Off",
    parentalModeTimer: "Timer",
    parentalModeStories: "Stories",
    parentalTimerLabel: "Duration (minutes)",
    parentalStoriesLabel: "Number of stories",
    parentalActivate: "Activate",
    parentalDeactivate: "Deactivate",
    parentalActive: "Active",
    parentalActiveTimer: (time) => `Timer: ${time} remaining`,
    parentalActiveStories: (n) => `${n} story(ies) allowed`,
    parentalWrongPin: "Wrong code",
    parentalWarningTitle: "Almost done!",
    parentalWarningTimer: (time) => `Only ${time} left!`,
    parentalWarningStories: (n) => `One more story and it's over! (${n} left)`,
    parentalLockTitle: "Good night!",
    parentalLockDetail: "Time is up. Time to rest.",
    parentalUnlock: "Unlock",
    parentalUnlockLabel: "Parent code to unlock",
    parentalNeedDownload: "Download at least one story before listening.",
    parentalMaxSelected: (n) => `Maximum ${n} story(ies) for this session.`,
    parentalChangePin: "Reset parent code",
    parentalResetMathHint: "Answer this question to reset the code:",
    parentalResetMathQuestion: (a, b) => `${a} × ${b} = ?`,
    parentalResetMathWrong: "Wrong answer",
    parentalNewPin: "New code (4 digits)",
    parentalConfirmPin: "Confirm new code",
    parentalSavePin: "Save code",
    parentalPinSaved: "Parent code saved!",
    parentalPinMismatch: "New codes do not match",
    parentalInvalidNewPin: "Code must be exactly 4 digits",
    parentalMinutesShort: "min",
    storiesCatalog: "Pack catalog",
    storiesCatalogHint: "Download a pack to unlock the stories inside.",
    storiesDownloadPack: "Download",
    storiesResumeDownload: "Resume",
    storiesPackReady: (n) => `${n} story(ies) added to your library!`,
    storiesDeletePack: (title) => `Delete "${title}" and all its stories?`,
    storiesNoDownloaded: "No downloaded stories. Open the catalog to download some!",
    storiesOpenCatalog: "Open catalog",
    storiesDownloadsActive: "downloads in progress",
    storiesDownloadCancelled: "Download stopped",
    storiesDownloadStoppedEmpty: "The download was interrupted.",
    storiesPartialSaved: (n) => `${n} story(ies) already available in your library`,
    storiesDownloadProgress: (written, total) => `${written} / ${total}`,
    storiesDownloadStatus: {
      preparing: "Preparing…",
      downloading: "Downloading…",
      paused: "Paused…",
      decrypting: "Decrypting…",
      unzipping: "Unzipping…",
      extracting: "Extracting…",
      saving: "Saving…",
    },
    playAlone: "Play Alone",
    playWithFriend: "2 Players",
    yourTurn: "Your Turn!",
    friendTurn: "Friend's Turn!",
    computerTurn: "Computer is thinking...",
    redWins: "Red Wins!",
    yellowWins: "Yellow Wins!",
    draw: "Draw!",
    puzzleGame: "Puzzle",
    puzzleInstruction: "Drag the pieces to recompose the image!",
    choosePuzzleImage: "Choose an image for your puzzle 🧩",
    chooseDifficulty: "Choose difficulty",
    piecesCount: (n) => `${n}x${n} (${n*n} pieces)`,
    savedPuzzles: "Puzzles in progress",
    continuePuzzle: "Continue puzzle",
    newPuzzle: "New puzzle",
    fromDevice: "From device",
    myPhoto: "My Photo",
    failedToPickImage: "Failed to pick image",
    enablePermissionsInSettings: "Enable permissions in settings!",
    error: "Error",
    success: "Success",
    listen: "Listen to instructions",
    mrMmeTitle: "Mr and Mrs",
    riddleTitle: "Riddles",
    jokes: {
      mr_mme: [
        { q: "Mr. and Mrs. 'Door' have a son?", a: "Matt! (Welcome mat...)" },
        { q: "Mr. and Mrs. 'Time' have a son?", a: "Justin! (Just in time...)" }
      ],
      devinettes: [
        { q: "What has to be broken before you can use it?", a: "An egg!" },
        { q: "What month of the year has 28 days?", a: "All of them!" }
      ]
    },
    voice: "en-US"
  },
  es: {
    appName: "Mi Mundo Mágico",
    play: "Jugar",
    color: "Colorear",
    bravo: "¡Bravo!",
    tryAgain: "¡Inténtalo de nuevo!",
    mathGame: "Matemáticas",
    logicGame: "Lógica",
    diffGame: "Diferencias",
    hangmanGame: "El Ahorcado",
    readingGame: "Lectura",
    jokesGame: "Chistes",
    takePhoto: "Tomar una foto",
    pickImage: "De la galería",
    blankPage: "Página en blanco",
    save: "Guardar",
    back: "Volver",
    score: "Puntuación",
    level: "Nivel",
    loading: "Cargando...",
    permissionDenied: "Permiso denegado",
    library: "Biblioteca",
    nouveau: "Nuevo",
    moi: "Yo",
    delete: "Eliminar",
    share: "Compartir",
    pin: "Fijar",
    done: "¡Listo!",
    understand: "¡Entendido!",
    help: "¿Necesitas ayuda?",
    next: "Siguiente",
    skip: "Saltar nivel",
    tutorialAdd: "¡Sumamos manzanas para contar!",
    tutorialSub: "¡Quitamos objetos!",
    tutorialMix: "¡Mira bien el signo (+ o -)!",
    tutorialMul: "¡Paquetes de números!",
    tutorialDiv: "¡Repartimos a partes iguales!",
    tutorialMental: "¡Cálculo Mental! Usa tu genio.",
    helpAdd: (a, b, ans) => `Imagina que tienes ${a} caramelos y te doy ${b}. ¡En total son ${ans}!`,
    helpSub: (a, b, ans) => `Imagina que tienes ${a} manzanas y te comes ${b}. ¡Te quedan ${ans}!`,
    helpMul: (a, b, ans) => `La multiplication es sumar varias veces. ¡${a} por ${b} es ${ans}!`,
    helpDiv: (a, b, ans) => `Reparte ${a} objetos entre ${b} amigos. ¡Cada uno tendrá ${ans}!`,
    logicInstruction: "¡Arrastra la forma al lugar correcto!",
    readingSyllables: "¡Une los sonidos idénticos!",
    readingWords: "¡Une las palabras gemelas!",
    readingPhrases: "¡Construye pequeñas historias!",
    readingLogic: "¡Responde a las preguntas sencillas!",
    connect4Game: "Conecta 4",
    storiesGame: "Cuentos",
    storiesSearchPlaceholder: "Buscar un cuento...",
    storiesAllSources: "Todos",
    storiesAllTypes: "Todo",
    storiesTypeStory: "Cuentos",
    storiesTypeSong: "Canciones",
    storiesSelected: "seleccionado(s)",
    storiesPlay: "Escuchar",
    storiesResume: "Continuar",
    storiesSelectDownloaded: "¡Selecciona cuentos descargados!",
    storiesNoProgress: "No hay lectura en curso.",
    storiesEmpty: "No se encontraron cuentos.",
    storiesEndingSoon: "¡Casi terminamos!",
    storiesEndingSoonDetail: (n) => `Los cuentos van a terminar. ¡Escuchaste ${n} ${n > 1 ? 'cuentos' : 'cuento'}!`,
    storiesGoodNight: "¡Buenas noches!",
    storiesGoodNightDetail: (n) => `Escuchaste ${n} ${n > 1 ? 'cuentos' : 'cuento'}. Hora de dormir.`,
    storiesBedtimeHint: "Pulsa el botón de encendido para apagar la tablet.",
    storiesProgress: (current, total) => `Cuento ${current} de ${total}`,
    parentalTitle: "Control parental",
    parentalPin: "Código de padres (4 dígitos)",
    parentalModeOff: "Desactivado",
    parentalModeTimer: "Temporizador",
    parentalModeStories: "Cuentos",
    parentalTimerLabel: "Duración (minutos)",
    parentalStoriesLabel: "Número de cuentos",
    parentalActivate: "Activar",
    parentalDeactivate: "Desactivar",
    parentalActive: "Activo",
    parentalActiveTimer: (time) => `Temporizador: ${time} restantes`,
    parentalActiveStories: (n) => `${n} cuento(s) permitido(s)`,
    parentalWrongPin: "Código incorrecto",
    parentalWarningTitle: "¡Casi terminamos!",
    parentalWarningTimer: (time) => `¡Solo quedan ${time}!`,
    parentalWarningStories: (n) => `¡Un cuento más y se acabó! (${n} restante)`,
    parentalLockTitle: "¡Buenas noches!",
    parentalLockDetail: "Se acabó el tiempo. Hora de descansar.",
    parentalUnlock: "Desbloquear",
    parentalUnlockLabel: "Código de padres para desbloquear",
    parentalNeedDownload: "Descarga al menos un cuento antes de escuchar.",
    parentalMaxSelected: (n) => `Máximo ${n} cuento(s) para esta sesión.`,
    parentalChangePin: "Restablecer código de padres",
    parentalResetMathHint: "Responde a esta pregunta para restablecer el código:",
    parentalResetMathQuestion: (a, b) => `${a} × ${b} = ?`,
    parentalResetMathWrong: "Respuesta incorrecta",
    parentalNewPin: "Nuevo código (4 dígitos)",
    parentalConfirmPin: "Confirmar nuevo código",
    parentalSavePin: "Guardar código",
    parentalPinSaved: "¡Código de padres guardado!",
    parentalPinMismatch: "Los códigos nuevos no coinciden",
    parentalInvalidNewPin: "El código debe tener exactamente 4 dígitos",
    parentalMinutesShort: "min",
    playAlone: "Jugar Solo",
    playWithFriend: "2 Jugadores",
    yourTurn: "¡Tu turno!",
    friendTurn: "¡Turno del amigo!",
    computerTurn: "El ordenador está pensando...",
    redWins: "¡Ganaron los Rojos!",
    yellowWins: "¡Ganaron los Amarillos!",
    draw: "¡Empate!",
    puzzleGame: "Puzle",
    puzzleInstruction: "¡Arrastra las piezas para recomponer la imagen!",
    choosePuzzleImage: "Elige una imagen para tu puzle 🧩",
    chooseDifficulty: "Elige la dificultad",
    piecesCount: (n) => `${n}x${n} (${n*n} piezas)`,
    savedPuzzles: "Puzles en curso",
    continuePuzzle: "Continuar puzle",
    newPuzzle: "Nuevo puzle",
    fromDevice: "Desde el dispositivo",
    myPhoto: "Mi Foto",
    failedToPickImage: "Error al seleccionar la imagen",
    enablePermissionsInSettings: "¡Activa los permisos en los ajustes!",
    error: "Error",
    success: "Éxito",
    listen: "Escuchar la consigna",
    mrMmeTitle: "Señor y Señora",
    riddleTitle: "Adivinanzas",
    jokes: {
      mr_mme: [
        { q: "¿Cómo se llama el hijo de los señores 'Cuesta'?", a: "Juan! (¡Juan Cuesta!)" }
      ],
      devinettes: [
        { q: "Oro parece, plata no es...", a: "¡El plátano!" },
        { q: "¿Qué tiene ojos pero no puede ver?", a: "¡Una patata!" }
      ]
    },
    voice: "es-ES"
  }
};

export const getStrings = (lang) => Strings[lang] || Strings.fr;
export default Strings;
